# --- !Ups
ALTER TABLE TRANSFORMER
ADD COLUMN version integer default 0;

ALTER TABLE TRANSFORMER
ADD COLUMN category varchar(255);

# --- !Downs
ALTER TABLE TRANSFORMER
DROP COLUMN version;

ALTER TABLE TRANSFORMER
ADD COLUMN category;
